### ISSUE TITLE
10 years since last post

### ISSUE THREAD

**Issue by maurges** [0xd34df00d/blog-comments#1]
WTF man я думал после бана на хабре твоя энергия направится в письмо а не в опенсурс.

Не думал переопубликовать некоторые статьи с хабра на собственный домен, раз они теперь недоступны?

**Comment by 0xd34df00d** [comment]
Да было бы что писать!

На хабре всё-таки немножко другая аудитория и, что даже важнее, есть возможность активно комментировать и обсуждать, и поэтому у статей туда немножко другая цель. Для личного блога хорошо подошли бы более старые статьи, которые я писал ещё до заведения стандалона, но они уже, собственно, старые :]

**Comment by lsap** [comment]
https://habr.com/en/news/840520/comments/#comment_27249020

**Comment by 0xd34df00d** [comment]
Можно закрывать, думаю.
