### ISSUE TITLE
Link to enummapset in NFA article 404

### ISSUE THREAD

**Issue by pmiddend** [0xd34df00d/blog-comments#3]
In https://0xd34df00d.me//posts/2024/09/naive-nfas.html, you're linking to https://hackage.hs.org/package/enummapset which is a 404.

**Comment by lsap** [comment]
Sorry for the intrusion https://hackage.haskell.org/package/enummapset

**Comment by 0xd34df00d** [comment]
I was overly `sed`-happy. Thanks, fixed!
